### ISSUE TITLE
Fix Erigon deployment

### ISSUE THREAD

**Issue by soad003** [graphsense/eth-client#1]

**Comment by mdragaschnig** [comment]
# Relevant changes since last deployment

## Consensus layer simplification

[Embedded Consensus Layer](https://github.com/ledgerwatch/erigon#embedded-consensus-layer)  since [v2.30](https://github.com/ledgerwatch/erigon/releases/tag/v2.30.0):

"By default, on Ethereum Mainnet, Görli, and Sepolia, the Engine API is disabled in favour of the Erigon **native** Embedded Consensus Layer. If you want to use an external Consensus Layer, run Erigon with flag --externalcl. Warning: Staking (block production) is not possible with the embedded CL – use --externalcl instead."

## Ethereum forks

Capella and Shanghai, both scheduled for 2023-04.


# Solution

Upgrade to at least https://github.com/ledgerwatch/erigon/releases/tag/v2.41.0

**Comment by defconst** [comment]
Fixed ce5d65f2783872a51e178db8329d556d630b28d4
